Changes for failed tests in Finsemble.
finos/FDC3-conformance-framework pull request #192
Opened 2023-03-17 16:44 UTC by gaganahluwalia

2023-03-23 09:41 UTC, kriswest approved these changes
LGTM

2023-03-24 10:16 UTC, robmoffat requested changes

2023-03-24 10:16 UTC, robmoffat commented on directories/local-conformance-2_0.finsemble.apps.json
> -  "comment": "AppD component config",
this file shouldn't have finsemble in the name - Finsemble uses the standard appD record now.

2023-03-24 10:16 UTC, robmoffat commented on src/mock/v2.0/intent-l.ts
> +import { closeWindowOnCompletion, onFdc3Ready } from "./mock-functions";
this shouldn't be intent-L, the intent-* mocks are for the Intents tests.  This is a basic test, so maybe call it "basic"?

2023-03-24 10:16 UTC, robmoffat commented on src/test/v2.0/support/intent-support-2.0.ts
> +    expect(typeof intentResult).to.be.oneOf(["object", 'undefined']);
remove this  - it's taken care of later.

2023-03-24 10:16 UTC, robmoffat commented on webpack.config.js
> +    "intent-l-v2.0": "./src/mock/v2.0/intent-l.ts",
rename here

2023-03-30 09:21 UTC, robmoffat approved these changes

2023-03-30 17:14 UTC, merged